"""Domain model for atomic, source-linked Evidence objects."""
from enum import Enum
from typing import Optional, Any, Dict
from pydantic import BaseModel, Field


class EvidenceSourceType(str, Enum):
    COMTRADE = "COMTRADE"
    GRAPH = "GRAPH"
    CONFIG_VALIDATOR = "CONFIG_VALIDATOR"
    EVENT_LOG = "EVENT_LOG"
    DOCUMENT = "DOCUMENT"
    INCIDENT_HISTORY = "INCIDENT_HISTORY"


class Evidence(BaseModel):
    """Atomic evidence fact extracted deterministically from domain tools."""
    evidence_id: str
    source_type: EvidenceSourceType
    source_id: str  # e.g., "INC-2026-001.CFG", "NEO4J-OGS01", "DOC-PROT-001"
    tool_name: str  # e.g., "analyze_comtrade_waveform", "query_substation_topology"
    fact: str  # Human-readable factual assertion
    structured_value: Any  # Machine-readable value (e.g. 3850.5, "CB12", True)
    unit: Optional[str] = None  # e.g. "A", "V", "ms", "Hz", "kV"
    timestamp: Optional[str] = None  # Specific millisecond timestamp if applicable
    provenance: str  # Exact channel, query, or chunk location (e.g., "Channel IC, sliding-window RMS")
    deterministic: bool = True  # True if generated by deterministic math/graph query
    metadata: Dict[str, Any] = Field(default_factory=dict)
